[build]
  publish = "dist"
  command = "curl --fail $FONTS_URL_1 --output public/fonts/font1.woff2 && curl --fail $FONTS_URL_2 --output public/fonts/font2.woff2 && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200